blank_issues_enabled: false  # Forces users to choose Bug Report or Feature Request
contact_links:
    -   name: 💬 Ask a Question
        url: https://github.com/NexcOrg/Nexc/discussions
        about: Please ask questions here instead of opening an issue.

    -   name: 🔐 Report a Security Vulnerability
        url: https://github.com/NexcOrg/Nexc/security/advisories/new
        about: Please do not report security flaws in public issues.